api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
  성경책뷰, 성경권뷰, 성경장뷰, 성경절뷰, 성경글뷰)

from .views import ArticleViewSet

schema_view = get_swagger_view(title='ahading API')

router = routers.DefaultRouter()
router.register('article', ArticleViewSet)
router.register('성경책', 성경책뷰)
router.register('성경권', 성경권뷰)
router.register('성경장', 성경장뷰)
router.register('성경절', 성경절뷰)
router.register('성경글', 성경글뷰)


urlpatterns = [
    path('', include(router.urls)),
    path('doc/', schema_view, name='연동방법'),
    path('api-auth/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

madie/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from boards import views
from accounts import views as accounts_views
from trot import views as trot_views
# from gallery import views as gallery_views
admin.autodiscover()

uid_token = r'(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'

urlpatterns = [
    path('vue/', TemplateView.as_view(template_name='vueIndex.html'), name='뷰테스트'),
    path('api/', include('api.urls')),
    path('성경/', include('bible.urls')),
    path('갤러리/', include('gallery.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='전체홈'),
    path('게시판/', include('boards.urls')),
    path('채팅/', TemplateView.as_view(template_name='채팅.html'), name='채팅'),
    
    path('사용자정보수정/', accounts_views.사용자정보수정뷰.as_view(), name='내계정정보'),

    path('가입/', accounts_views.가입, name='가입'),
    path('로그인/', auth_views.LoginView.as_view(template_name='로그인.html'), name='로그인'),
    path('로그아웃/', auth_views.LogoutView.as_view(), name='로그아웃'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'), name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    re_path('reset/{}/'.format(uid_token),
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models

#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import uuid
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from django.urls import reverse

class Album(models.Model):
    title = models.CharField(max_length=70)
    description = models.TextField(max_length=1024)
    thumb = ProcessedImageField(upload_to='', processors=[ResizeToFit(300)], format='JPEG', options={'quality': 90})
    tags = models.CharField(max_length=250)
    is_visible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=50, unique=True)

    def get_absolute_url(self):
       return reverse('album', kwargs={'slug':self.slug})

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class AlbumImage(models.Model):
    image = ProcessedImageField(upload_to='albums', processors=[ResizeToFit(1280)], format='JPEG', options={'quality': 70})
    thumb = ProcessedImageField(upload_to='albums', processors=[ResizeToFit(300)], format='JPEG', options={'quality': 80})
    album = models.ForeignKey('album', on_delete=models.PROTECT)
    alt = models.CharField(max_length=255, default=uuid.uuid4)
    created = models.DateTimeField(auto_now_add=True)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    slug = models.SlugField(max_length=70, default=uuid.uuid4, editable=False)

trot/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


class 이미지텝(models.Model):
    파일 = models.ImageField()
    설명 = models.CharField(max_length=255, blank=True)
    시간 = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '이미지'
        verbose_name_plural = '이미지들'

    def __str__(self):
        return self.설명


class Article(models.Model):
    article_id = models.AutoField(primary_key=True)
    article_heading = models.CharField(max_length=250)
    article_body = models.TextField()

trot/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import 이미지텝

class 이미지폼(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    넓이 = forms.FloatField(widget=forms.HiddenInput())
    높이 = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = 이미지텝
        fields = ('파일', 'x', 'y', '넓이', '높이', )

    def save(self):
        사진 = super(이미지폼, self).save()
        print("한마디 = ", dir(사진))

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('넓이')
        h = self.cleaned_data.get('높이')

        원형이미지 = Image.open(사진.file)
        자른이미지 = 원형이미지.crop((x, y, w+x, h+y))
        변형이미지 = 자른이미지.resize((200, 200), Image.ANTIALIAS)
        변형이미지.save(사진.file.path)

        return 변형이미지

trot/views.py
from django.shortcuts import render, redirect

from .models import 이미지텝
from .forms import 이미지폼


def 이미지뷰(request):
    이미지들 = 이미지텝.objects.all()
    if request.method == 'POST':
        print("한마디", request.POST)
        print("한마디", request.FILES)
        form = 이미지폼(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('이미지목록')
    else:
        form = 이미지폼()
    return render(request, 'trot/이미지목록.html', {'form': form, '이미지들': 이미지들})

trot/templates/trot/이미지기본.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cropper.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

trot/templates/trot/이미지목록.html
{% extends 'trot/이미지기본.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in 이미지들 %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.파일.url }}" class="thumbnail">
      </div>      
    {% endfor %}
  </div>

  <div class="media">
    {% for photo in 이미지들 %}
    <img class="mr-3" src="{{ photo.파일.url }}" alt="Generic placeholder image">
    <div class="media-body">
      <h5 class="mt-0">Media heading</h5>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
    {% endfor %}
  </div>

{% endblock %}